"""about author

Revision ID: 30640622f534
Revises: f72f91419f4d
Create Date: 2022-09-14 13:26:42.164864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30640622f534'
down_revision = 'f72f91419f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viewrs', sa.Column('about_author', sa.Text(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viewrs', 'about_author')
    # ### end Alembic commands ###
