"""username

Revision ID: 63cc097b559f
Revises: df0e89b83784
Create Date: 2022-09-12 14:34:31.873845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63cc097b559f'
down_revision = 'df0e89b83784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viewrs', sa.Column('username', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'viewrs', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'viewrs', type_='unique')
    op.drop_column('viewrs', 'username')
    # ### end Alembic commands ###
