"""Initial Migration

Revision ID: 7780dece58cd
Revises: 
Create Date: 2022-09-09 11:59:06.801308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7780dece58cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viewrs', sa.Column('profession', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viewrs', 'profession')
    # ### end Alembic commands ###
