"""empty message

Revision ID: 79f139224bc9
Revises: 606dba4b1c8b
Create Date: 2022-09-14 17:04:53.592160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f139224bc9'
down_revision = '606dba4b1c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viewrs', sa.Column('profile_pic', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viewrs', 'profile_pic')
    # ### end Alembic commands ###
