"""password field

Revision ID: c61d360cd70d
Revises: 7780dece58cd
Create Date: 2022-09-09 15:20:01.512645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61d360cd70d'
down_revision = '7780dece58cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viewrs', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viewrs', 'password_hash')
    # ### end Alembic commands ###
